language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - hhvm

services:
    - redis
    - memcached
    - mongodb

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
    - ./build/all.sh
    - if [[ "$TRAVIS_PHP_VERSION" == '5.5' || "$TRAVIS_PHP_VERSION" == '5.6' ]]; then ./build/5.x.sh; fi
    - if [ "$TRAVIS_PHP_VERSION" == '7.0' ]; then ./build/7.x.sh; fi
    - if [ "$TRAVIS_PHP_VERSION" == 'hhvm' ]; then ./build/hhvm.sh; fi
    - travis_retry composer self-update

install:
    - COMPONENTS=$(find src/ -mindepth 3 -type f -name phpunit.xml.dist -printf '%h\n')
    - travis_retry composer install --no-interaction --prefer-source

script:
    - echo "$COMPONENTS" | parallel --gnu 'vendor/bin/phpunit --exclude-group tty,benchmark,intl-data {}'

after_success:
    - if [ "$TRAVIS_PHP_VERSION" == '7.0' ]; codecov; fi

sudo: required
dist: precise

notifications:
    email: false
