language: php

php:
  - 5.5
  - 5.6
  - 7.0
  # more php versions

env:
  matrix:
    - ADAPTER=bar PHPUNIT_FILE=filepath
    - ADAPTER=foo
    - ADAPTER=common

matrix:
  fast_finish: true

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - openssl aes-256-cbc -K $encrypted_99f52e9ffe4d_key -iv $encrypted_99f52e9ffe4d_iv -in .travis/sshkey.enc -out .travis/sshkey -d
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/sshkey # this key should have push access
  - ssh-add .travis/sshkey # Add the ssh key to travis. This will give travis push access

install:

before_script:

script:

after_success:
#  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PHP_VERSION" = "7.0" ] && [ "$ADAPTER" = "common" ]; then sh .travis/subsplit.sh; fi;

sudo: true

notifications:
  email: false