language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# env:
#   matrix:
#     - ADAPTER=bar PHPUNIT_FILE=filepath
#     - ADAPTER=foo
#     - ADAPTER=common

matrix:
  include:
    - php: 5.6
      env: SEND_COVERAGE=true
  fast_finish: true
  allow_failures:
    - php: hhvm

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - if [[ $TRAVIS_PHP_VERSION != hhvm && SEND_COVERAGE != true ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - openssl aes-256-cbc -K $encrypted_99f52e9ffe4d_key -iv $encrypted_99f52e9ffe4d_iv -in .travis/sshkey.enc -out .travis/sshkey -d
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/sshkey # this key should have push access
  - ssh-add .travis/sshkey # Add the ssh key to travis. This will give travis push access

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit -c phpunit.xml.dist

after_success:
#  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PHP_VERSION" = "7.0" ] && [ "$ADAPTER" = "common" ]; then sh .travis/subsplit.sh; fi;

sudo: true

notifications:
  email: false