language: php
sudo: false

matrix:
    include:
      - php: 7.1
      - php: 8.0
      - php: 8.1

cache:
    directories:
      - "$HOME/.composer/cache"

install:
    - composer update --prefer-dist --prefer-stable

script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - pip install --user codecov && codecov

notifications:
    email: false
